version: "3.8"

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_PASSWORD: "docker"
      POSTGRESQL_MAX_CONNECTIONS: 100000
    volumes:
      - "postgresql_data:/bitnami/postgresql"
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9094:9094"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    volumes:
      - "kafka_data:/bitnami/kafka"

volumes:
  postgresql_data:
  kafka_data:
